export enum Role {
    REGISTERED_USER = "REGISTERED_USER",
    CUSTOMER = "CUSTOMER",
    TRAVEL_AGENT = "TRAVEL_AGENT",
    ADMINISTRATOR = "ADMINISTRATOR",
    CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
    PARTNER = "PARTNER",
    FINANCE = "FINANCE",
}
